### ISSUE TITLE
Request timeout.

### ISSUE THREAD

**Issue by JostCrow** [taigaio/taiga-back#602]
GUnicorn error log
[2016-02-05 11:11:40 +0000] [997] [CRITICAL] WORKER TIMEOUT (pid:1090)
[2016-02-05 11:11:40 +0000] [2178] [INFO] Booting worker with pid: 2178

Nginx access log
10.0.2.2 - - [05/Feb/2016:11:11:40 +0000] "PATCH /api/v1/issues/87 HTTP/1.1" 504 593 "http://taiga.maykinmedia.nl/project/admin-idea-lab/issue/269" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36"

Nginx error log
2016/02/05 11:11:40 [error] 1123#0: *22 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.0.2.2, server: _, request: "PATCH /api/v1/issues/87 HTTP/1.1", upstream: "http://127.0.0.1:8001/api/v1/issues/87", host: "taiga.maykinmedia.nl", referrer: "http://taiga.maykinmedia.nl/project/admin-idea-lab/issue/269"

Can you please help me what is going wrong or how I can get more information?

**Comment by superalex** [comment]
Hello @JostCrow did you check the logs folder from the Taiga user to see if there is something wrong?

**Comment by JostCrow** [comment]
No I did not. I will give an update soon

On Fri, 5 Feb 2016 13:08 Alejandro <notifications@github.com> wrote:

> Hello @JostCrow <https://github.com/JostCrow> did you check the logs
> folder from the Taiga user to see if there is something wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/602#issuecomment-180321993>.
>
-- 

Groeten,

Jorik Kraaikamp

**Comment by superalex** [comment]
Great! :+1:

**Comment by JostCrow** [comment]
With folder are you talking about? the one in taiga-back/user? Because that folder does not contain anything useful.

I also ran the tests locally and this where the results.
==== 11 failed, 821 passed, 2 xfailed, 1 xpassed in 798.04 seconds ===

**Comment by superalex** [comment]
Yes, the one in the home of taiga user.

Those 11 failing tests should be working...may be that's the reason. What's the failure from those tests?

**Comment by JostCrow** [comment]
The items in my original comment has the useful logs. 

This are the failing tests
```
================================================================================================================== FAILURES ==================================================================================================================
_____________________________________________________________________________________________________ test_proccessor_valid_user_mention _____________________________________________________________________________________________________

    def test_proccessor_valid_user_mention():
        factories.UserFactory(username="user1", full_name="test name")
        result = render(dummy_project, "**@user1**")
        expected_result = "<p><strong><a class=\"mention\" href=\"http://localhost:9001/profile/user1\" title=\"test name\">@user1</a></strong></p>"
>       assert result == expected_result
E       assert '<p><strong><...</strong></p>' == '<p><strong><a...</strong></p>'
E         Skipping 33 identical leading characters in diff, use -v to show
E         - f="http://taiga.maykinmedia.nl/profile/user1" title="test name">@user1</a></strong></p>
E         ?            ^^^^^^^^^^^^^^^^^^^
E         + f="http://localhost:9001/profile/user1" title="test name">@user1</a></strong></p>
E         ?           ++++++++ ^^^^^

tests/integration/test_mdrender.py:38: AssertionError
_____________________________________________________________________________________________________ test_proccessor_valid_us_reference _____________________________________________________________________________________________________

    def test_proccessor_valid_us_reference():
        with patch("taiga.mdrender.extensions.references.get_instance_by_ref") as mock:
            instance = mock.return_value
            instance.content_type.model = "userstory"
            instance.content_object.subject = "test"
            result = render(dummy_project, "**#1**")
            expected_result = '<p><strong><a class="reference user-story" href="http://localhost:9001/project/test/us/1" title="#1 test">#1</a></strong></p>'
>           assert result == expected_result
E           assert '<p><strong><...</strong></p>' == '<p><strong><a...</strong></p>'
E             Skipping 46 identical leading characters in diff, use -v to show
E             - f="http://taiga.maykinmedia.nl/project/test/us/1" title="#1 test">#1</a></strong></p>
E             ?            ^^^^^^^^^^^^^^^^^^^
E             + f="http://localhost:9001/project/test/us/1" title="#1 test">#1</a></strong></p>
E             ?           ++++++++ ^^^^^

tests/unit/test_mdrender.py:48: AssertionError
___________________________________________________________________________________________________ test_proccessor_valid_issue_reference ____________________________________________________________________________________________________

    def test_proccessor_valid_issue_reference():
        with patch("taiga.mdrender.extensions.references.get_instance_by_ref") as mock:
            instance = mock.return_value
            instance.content_type.model = "issue"
            instance.content_object.subject = "test"
            result = render(dummy_project, "**#2**")
            expected_result = '<p><strong><a class="reference issue" href="http://localhost:9001/project/test/issue/2" title="#2 test">#2</a></strong></p>'
>           assert result == expected_result
E           assert '<p><strong><...</strong></p>' == '<p><strong><a...</strong></p>'
E             Skipping 41 identical leading characters in diff, use -v to show
E             - f="http://taiga.maykinmedia.nl/project/test/issue/2" title="#2 test">#2</a></strong></p>
E             ?            ^^^^^^^^^^^^^^^^^^^
E             + f="http://localhost:9001/project/test/issue/2" title="#2 test">#2</a></strong></p>
E             ?           ++++++++ ^^^^^

tests/unit/test_mdrender.py:58: AssertionError
____________________________________________________________________________________________________ test_proccessor_valid_task_reference ____________________________________________________________________________________________________

    def test_proccessor_valid_task_reference():
        with patch("taiga.mdrender.extensions.references.get_instance_by_ref") as mock:
            instance = mock.return_value
            instance.content_type.model = "task"
            instance.content_object.subject = "test"
            result = render(dummy_project, "**#3**")
            expected_result = '<p><strong><a class="reference task" href="http://localhost:9001/project/test/task/3" title="#3 test">#3</a></strong></p>'
>           assert result == expected_result
E           assert '<p><strong><...</strong></p>' == '<p><strong><a...</strong></p>'
E             Skipping 40 identical leading characters in diff, use -v to show
E             - f="http://taiga.maykinmedia.nl/project/test/task/3" title="#3 test">#3</a></strong></p>
E             ?            ^^^^^^^^^^^^^^^^^^^
E             + f="http://localhost:9001/project/test/task/3" title="#3 test">#3</a></strong></p>
E             ?           ++++++++ ^^^^^

tests/unit/test_mdrender.py:68: AssertionError
____________________________________________________________________________________________________________ test_render_wikilink ____________________________________________________________________________________________________________

    def test_render_wikilink():
        expected_result = "<p><a class=\"reference wiki\" href=\"http://localhost:9001/project/test/wiki/test\" title=\"test\">test</a></p>"
>       assert render(dummy_project, "[[test]]") == expected_result
E       assert '<p><a class=...>test</a></p>' == '<p><a class="...>test</a></p>'
E         - <p><a class="reference wiki" href="http://taiga.maykinmedia.nl/project/test/wiki/test" title="test">test</a></p>
E         ?                                            ^^^^^^^^^^^^^^^^^^^
E         + <p><a class="reference wiki" href="http://localhost:9001/project/test/wiki/test" title="test">test</a></p>
E         ?                                           ++++++++ ^^^^^

tests/unit/test_mdrender.py:103: AssertionError
___________________________________________________________________________________________________________ test_render_wikilink_1 ___________________________________________________________________________________________________________

    def test_render_wikilink_1():
        expected_result = "<p><a class=\"reference wiki\" href=\"http://localhost:9001/project/test/wiki/test\" title=\"test\">test</a></p>"
>       assert render(dummy_project, "[[test]]") == expected_result
E       assert '<p><a class=...>test</a></p>' == '<p><a class="...>test</a></p>'
E         - <p><a class="reference wiki" href="http://taiga.maykinmedia.nl/project/test/wiki/test" title="test">test</a></p>
E         ?                                            ^^^^^^^^^^^^^^^^^^^
E         + <p><a class="reference wiki" href="http://localhost:9001/project/test/wiki/test" title="test">test</a></p>
E         ?                                           ++++++++ ^^^^^

tests/unit/test_mdrender.py:108: AssertionError
___________________________________________________________________________________________________________ test_render_wikilink_2 ___________________________________________________________________________________________________________

    def test_render_wikilink_2():
        expected_result = "<p><a class=\"reference wiki\" href=\"http://localhost:9001/project/test/wiki/test-page\" title=\"test page\">test page</a></p>"
>       assert render(dummy_project, "[[test page]]") == expected_result
E       assert '<p><a class=... page</a></p>' == '<p><a class="... page</a></p>'
E         - <p><a class="reference wiki" href="http://taiga.maykinmedia.nl/project/test/wiki/test-page" title="test page">test page</a></p>
E         ?                                            ^^^^^^^^^^^^^^^^^^^
E         + <p><a class="reference wiki" href="http://localhost:9001/project/test/wiki/test-page" title="test page">test page</a></p>
E         ?                                           ++++++++ ^^^^^

tests/unit/test_mdrender.py:113: AssertionError
___________________________________________________________________________________________________________ test_render_wikilink_3 ___________________________________________________________________________________________________________

    def test_render_wikilink_3():
        expected_result = "<p><a class=\"reference wiki\" href=\"http://localhost:9001/project/test/wiki/testpage\" title=\"TestPage\">TestPage</a></p>"
>       assert render(dummy_project, "[[TestPage]]") == expected_result
E       assert '<p><a class=...tPage</a></p>' == '<p><a class="...tPage</a></p>'
E         - <p><a class="reference wiki" href="http://taiga.maykinmedia.nl/project/test/wiki/testpage" title="TestPage">TestPage</a></p>
E         ?                                            ^^^^^^^^^^^^^^^^^^^
E         + <p><a class="reference wiki" href="http://localhost:9001/project/test/wiki/testpage" title="TestPage">TestPage</a></p>
E         ?                                           ++++++++ ^^^^^

tests/unit/test_mdrender.py:118: AssertionError
___________________________________________________________________________________________________ test_render_wikilink_with_custom_title ___________________________________________________________________________________________________

    def test_render_wikilink_with_custom_title():
        expected_result = "<p><a class=\"reference wiki\" href=\"http://localhost:9001/project/test/wiki/test\" title=\"custom\">custom</a></p>"
>       assert render(dummy_project, "[[test|custom]]") == expected_result
E       assert '<p><a class=...ustom</a></p>' == '<p><a class="...ustom</a></p>'
E         - <p><a class="reference wiki" href="http://taiga.maykinmedia.nl/project/test/wiki/test" title="custom">custom</a></p>
E         ?                                            ^^^^^^^^^^^^^^^^^^^
E         + <p><a class="reference wiki" href="http://localhost:9001/project/test/wiki/test" title="custom">custom</a></p>
E         ?                                           ++++++++ ^^^^^

tests/unit/test_mdrender.py:123: AssertionError
___________________________________________________________________________________________________ test_render_wikilink_slug_to_wikipages ___________________________________________________________________________________________________

    def test_render_wikilink_slug_to_wikipages():
        expected_result = "<p><a class=\"reference wiki\" href=\"http://localhost:9001/project/test/wiki/wiki_page\" title=\"wiki page\">wiki</a></p>"
>       assert render(dummy_project, "[wiki](wiki_page \"wiki page\")") == expected_result
E       assert '<p><a class=...>wiki</a></p>' == '<p><a class="...>wiki</a></p>'
E         - <p><a class="reference wiki" href="http://taiga.maykinmedia.nl/project/test/wiki/wiki_page" title="wiki page">wiki</a></p>
E         ?                                            ^^^^^^^^^^^^^^^^^^^
E         + <p><a class="reference wiki" href="http://localhost:9001/project/test/wiki/wiki_page" title="wiki page">wiki</a></p>
E         ?                                           ++++++++ ^^^^^

tests/unit/test_mdrender.py:128: AssertionError
_________________________________________________________________________________________________ test_render_wikilink_relative_to_absolute __________________________________________________________________________________________________

    def test_render_wikilink_relative_to_absolute():
        expected_result = "<p><a href=\"http://localhost:9001/project/test/\">test project</a></p>"
>       assert render(dummy_project, "[test project](/project/test/)") == expected_result
E       assert '<p><a href="...oject</a></p>' == '<p><a href="h...oject</a></p>'
E         - <p><a href="http://taiga.maykinmedia.nl/project/test/">test project</a></p>
E         ?                     ^^^^^^^^^^^^^^^^^^^
E         + <p><a href="http://localhost:9001/project/test/">test project</a></p>
E         ?                    ++++++++ ^^^^^

tests/unit/test_mdrender.py:133: AssertionError
======================================================================================= 11 failed, 821 passed, 2 xfailed, 1 xpassed in 798.04 seconds ========================================================================================
```

**Comment by superalex** [comment]
I've tried accessing your API and the http://taiga.maykinmedia.nl/api/v1/projects is giving an "AttributeError", 'Manager' object has no attribute '_prefetch_related_lookups' it seems it could be related with the django version. In http://stackoverflow.com/questions/28192858/encodeerror-queryset-object-has-no-attribute-prefetch-related-lookups they suggest customizing your SECRET_KEY setting in your local.py file, could you try please try it?

**Comment by JostCrow** [comment]
I customized SECRET_KEY. This still did not solve the problem.

**Comment by superalex** [comment]
In https://github.com/taigaio/taiga-back/issues/603 a user reported it was an issue with django1.8.6 but we couldn't reproduce it, could you try installing django 1.8.9?

`pip install "Django==1.8.9"       `

**Comment by JostCrow** [comment]
Yes I willtry to install 1.8.9

On Mon, 8 Feb 2016 12:50 Alejandro <notifications@github.com> wrote:

> In #603 <https://github.com/taigaio/taiga-back/issues/603> a user
> reported it was an issue with django1.8.6 but we couldn't reproduce it,
> could you try installing django 1.8.9?
>
> pip install "Django==1.8.9"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/602#issuecomment-181333109>.
>
-- 

Groeten,

Jorik Kraaikamp

**Comment by JostCrow** [comment]
Also upgrading to django 1.8.9 does not work.

**Comment by superalex** [comment]
Did you restart taiga-back after upgrading?

`circusctl restart taiga`

**Comment by JostCrow** [comment]
yes I did. I also restarted nginx to be sure that it was restarted.

**Comment by superalex** [comment]
Nginx is just doing a proxy pass so restarting shouldn't be necessary. Could you check if under your taiga virtualenv (workon taiga) the django version is updated? (pip show django)

**Comment by JostCrow** [comment]
Yes 1.8.9 is installed instead of django 1.8.6

![screenshot from 2016-02-08 14 54 29](https://cloud.githubusercontent.com/assets/390575/12887354/f0051ca6-ce73-11e5-8cf8-9425f619ba6c.png)

**Comment by siliconalchemy** [comment]
Hi, I had the same error ('Manager' object has no attribute '_prefetch_related_lookups').  I have three identical nodes with django 1.8.6 and one worked perfectly and the other two had this issue.  I realised that I didn't follow the setup doc fully by ensuring that I was in a virtualenv.  The setup doc isn't very clear about this and I'm on centos.  By following the latest doc:
https://virtualenvwrapper.readthedocs.org/en/latest/
And ensuring virtualenwrapper was fully working, I then reinstalled the requirements in a virtualenv and this error disappeared on both nodes.

**Comment by superalex** [comment]
Thank you very much @siliconalchemy , @jespino could it be that something similar is happening in your environment?

**Comment by JostCrow** [comment]
For me this is not the case. I completely removed the virtualenv and installed it again to be sure that it is installed correctly. But sadly after all those things it did not work the way I wanted.

**Comment by superalex** [comment]
We should be moving to django1.9 as soon as we can, could you please try with django1.9?

**Comment by JostCrow** [comment]
I already did. But I was not able to see the data anymore

On Tue, 9 Feb 2016 10:38 Alejandro <notifications@github.com> wrote:

> We should be moving to django1.9 as soon as we can, could you please try
> with django1.9?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/602#issuecomment-181783711>.
>
-- 

Groeten,

Jorik Kraaikamp

**Comment by superalex** [comment]
The data?

**Comment by JostCrow** [comment]
Yes I already had some projects in there. But after I updated to django 1.9
I was unable to see any data.

On Tue, 9 Feb 2016 at 10:48 Alejandro <notifications@github.com> wrote:

> The data?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/602#issuecomment-181786089>.
>
-- 

Groeten,

Jorik Kraaikamp

**Comment by superalex** [comment]
Ok!, and did you check your logs folder after the update to django1.9?

**Comment by JostCrow** [comment]
No i did not. I will let you know what was in it later today.

On Tue, 9 Feb 2016 at 10:54 Alejandro <notifications@github.com> wrote:

> Ok!, and did you check your logs folder after the update to django1.9?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/602#issuecomment-181788743>.
>
-- 

Groeten,

Jorik Kraaikamp

**Comment by superalex** [comment]
Thank you very much!

**Comment by JostCrow** [comment]
The logs did not say anything. After locally trying to start the server I got the null handler error. I solved that by removing the null handler. 

But afterwards I got this error.
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/taiga-back/taiga/base/apps.py", line 20, in <module>
    from .signals.thumbnails import connect_thumbnail_signals
  File "/home/vagrant/taiga-back/taiga/base/signals/thumbnails.py", line 19, in <module>
    from easy_thumbnails.files import get_thumbnailer
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/easy_thumbnails/files.py", line 14, in <module>
    from easy_thumbnails import engine, exceptions, models, utils, signals, storage
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/easy_thumbnails/models.py", line 55, in <module>
    class File(models.Model):
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by superalex** [comment]
We have to check what's happening on django1.9

About your original problem, is this a clean installation or you updated it from a different version?, as using taiga-vagrant, is it possible that you destroy your vagrant instance and create it from the beginning?

**Comment by JostCrow** [comment]
If I were to do that. Would I loose the data?

On Tue, 9 Feb 2016 at 11:31 Alejandro <notifications@github.com> wrote:

> We have to check what's happening on django1.9
>
> About your original problem, is this a clean installation or you updated
> it from a different version?, as using taiga-vagrant, is it possible that
> you destroy your vagrant instance and create it from the beginning?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/602#issuecomment-181805067>.
>
-- 

Groeten,

Jorik Kraaikamp

**Comment by superalex** [comment]
Yes, it would be lost but you could get a postgresql dump, destroy the vagrant instance and restore the dump.

**Comment by JostCrow** [comment]
Ok. I will make a dump and then destroy it.

On Tue, 9 Feb 2016 at 11:51 Alejandro <notifications@github.com> wrote:

> Yes, it would be lost but you could get a postgresql dump, destroy the
> vagrant instance and restore the dump.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/602#issuecomment-181813562>.
>
-- 

Groeten,

Jorik Kraaikamp

**Comment by JostCrow** [comment]
Reinstalling it solved the issue. Thanks.

**Comment by superalex** [comment]
Great!
